/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarRecord;
import ElasticSearch.ElasticSearchClass;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author manasa
 */
public class CarCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CarCustomerJPanel
     */
    private CarRecord carRecord;
    private JPanel userProcessContainer;
    private String user;
    private ElasticSearchClass elasticSearchClass;
    public CarCustomerJPanel(JPanel userProcessContainer, CarRecord carRecord,String user,ElasticSearchClass elasticSearchClass) {
        initComponents();
        this.carRecord = carRecord;
        this.userProcessContainer = userProcessContainer;
        this.user = user;
        this.elasticSearchClass = elasticSearchClass;
                makePanel.setVisible(false);
        seatPanel.setVisible(false);
        serialPanel.setVisible(false);
        cityPanel.setVisible(false);
        modelPanel.setVisible(false);
        yearPanel.setVisible(false);
        availPanel.setVisible(false);
       
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSearchBySeats = new javax.swing.JButton();
        btnSearchBySerial = new javax.swing.JButton();
        btnSearchByModel = new javax.swing.JButton();
        btnSearchByCity = new javax.swing.JButton();
        btnSearchByAvail = new javax.swing.JButton();
        btnSearchByMake = new javax.swing.JButton();
        btnSearchByYear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seatPanel = new javax.swing.JPanel();
        txtMinSeats = new javax.swing.JTextField();
        txtMaxSeats = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSeats = new javax.swing.JButton();
        serialPanel = new javax.swing.JPanel();
        btnSerial1 = new javax.swing.JButton();
        txtSerial1 = new javax.swing.JTextField();
        modelPanel = new javax.swing.JPanel();
        btnModel = new javax.swing.JButton();
        txtModel = new javax.swing.JTextField();
        cityPanel = new javax.swing.JPanel();
        btnTravelCity = new javax.swing.JButton();
        txtTravelCity = new javax.swing.JTextField();
        availPanel = new javax.swing.JPanel();
        btnAvailable = new javax.swing.JRadioButton();
        btnNotAvailable = new javax.swing.JRadioButton();
        btnAvail = new javax.swing.JButton();
        makePanel = new javax.swing.JPanel();
        btnMake = new javax.swing.JButton();
        txtMake = new javax.swing.JTextField();
        yearPanel = new javax.swing.JPanel();
        btnMakeYear = new javax.swing.JButton();
        txtMakeYear = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAllCars1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 102));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        btnBack.setText("GO BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        btnSearchBySeats.setText("Search Cars by Seats");
        btnSearchBySeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBySeatsActionPerformed(evt);
            }
        });

        btnSearchBySerial.setText("Search Cars by Serial Number");
        btnSearchBySerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBySerialActionPerformed(evt);
            }
        });

        btnSearchByModel.setText("Search Cars by Model");
        btnSearchByModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByModelActionPerformed(evt);
            }
        });

        btnSearchByCity.setText("Search Cars by City");
        btnSearchByCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByCityActionPerformed(evt);
            }
        });

        btnSearchByAvail.setText("Search Cars by Availability");
        btnSearchByAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByAvailActionPerformed(evt);
            }
        });

        btnSearchByMake.setText("Search Cars by Make");
        btnSearchByMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByMakeActionPerformed(evt);
            }
        });

        btnSearchByYear.setText("Search Cars By Year");
        btnSearchByYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByYearActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Search Cars Based on Type Below");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Know the Cars Already?");

        seatPanel.setBackground(new java.awt.Color(0, 153, 153));
        seatPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        seatPanel.setForeground(new java.awt.Color(204, 204, 204));

        txtMinSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinSeatsActionPerformed(evt);
            }
        });

        txtMaxSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxSeatsActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Minimum Seats");

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Maximum Seats");

        btnSeats.setText("Search");
        btnSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seatPanelLayout = new javax.swing.GroupLayout(seatPanel);
        seatPanel.setLayout(seatPanelLayout);
        seatPanelLayout.setHorizontalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeats))
        );
        seatPanelLayout.setVerticalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(btnSeats))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        serialPanel.setBackground(new java.awt.Color(0, 153, 153));
        serialPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        serialPanel.setForeground(new java.awt.Color(204, 204, 204));

        btnSerial1.setText("Search");
        btnSerial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerial1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout serialPanelLayout = new javax.swing.GroupLayout(serialPanel);
        serialPanel.setLayout(serialPanelLayout);
        serialPanelLayout.setHorizontalGroup(
            serialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSerial1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSerial1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        serialPanelLayout.setVerticalGroup(
            serialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serialPanelLayout.createSequentialGroup()
                .addGroup(serialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serialPanelLayout.createSequentialGroup()
                        .addComponent(btnSerial1)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(serialPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtSerial1)))
                .addContainerGap())
        );

        modelPanel.setBackground(new java.awt.Color(0, 153, 153));
        modelPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        modelPanel.setForeground(new java.awt.Color(204, 204, 204));

        btnModel.setBackground(new java.awt.Color(204, 204, 204));
        btnModel.setText("Search");
        btnModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modelPanelLayout = new javax.swing.GroupLayout(modelPanel);
        modelPanel.setLayout(modelPanelLayout);
        modelPanelLayout.setHorizontalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modelPanelLayout.createSequentialGroup()
                .addComponent(txtModel, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        modelPanelLayout.setVerticalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modelPanelLayout.createSequentialGroup()
                .addGroup(modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtModel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        cityPanel.setBackground(new java.awt.Color(0, 153, 153));
        cityPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        cityPanel.setForeground(new java.awt.Color(204, 204, 204));

        btnTravelCity.setText("Search");
        btnTravelCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cityPanelLayout = new javax.swing.GroupLayout(cityPanel);
        cityPanel.setLayout(cityPanelLayout);
        cityPanelLayout.setHorizontalGroup(
            cityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityPanelLayout.createSequentialGroup()
                .addComponent(txtTravelCity, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTravelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cityPanelLayout.setVerticalGroup(
            cityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityPanelLayout.createSequentialGroup()
                .addGroup(cityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTravelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTravelCity))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        availPanel.setBackground(new java.awt.Color(0, 153, 153));
        availPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        availPanel.setForeground(new java.awt.Color(204, 204, 204));

        btnAvailable.setForeground(new java.awt.Color(204, 204, 204));
        btnAvailable.setText("Available Cars");
        btnAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableActionPerformed(evt);
            }
        });

        btnNotAvailable.setForeground(new java.awt.Color(204, 204, 204));
        btnNotAvailable.setText("Not Available Cars");

        btnAvail.setText("Search");
        btnAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout availPanelLayout = new javax.swing.GroupLayout(availPanel);
        availPanel.setLayout(availPanelLayout);
        availPanelLayout.setHorizontalGroup(
            availPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availPanelLayout.createSequentialGroup()
                .addComponent(btnAvailable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotAvailable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvail))
        );
        availPanelLayout.setVerticalGroup(
            availPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, availPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(availPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvailable)
                    .addComponent(btnNotAvailable)
                    .addComponent(btnAvail)))
        );

        makePanel.setBackground(new java.awt.Color(0, 153, 153));
        makePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        makePanel.setForeground(new java.awt.Color(204, 204, 204));

        btnMake.setText("Search");
        btnMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeActionPerformed(evt);
            }
        });

        txtMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMakeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout makePanelLayout = new javax.swing.GroupLayout(makePanel);
        makePanel.setLayout(makePanelLayout);
        makePanelLayout.setHorizontalGroup(
            makePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMake, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );
        makePanelLayout.setVerticalGroup(
            makePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(makePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMake))
            .addGroup(makePanelLayout.createSequentialGroup()
                .addComponent(txtMake)
                .addGap(3, 3, 3))
        );

        yearPanel.setBackground(new java.awt.Color(0, 153, 153));
        yearPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        yearPanel.setForeground(new java.awt.Color(204, 204, 204));

        btnMakeYear.setBackground(new java.awt.Color(0, 153, 153));
        btnMakeYear.setText("Search");
        btnMakeYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeYearActionPerformed(evt);
            }
        });

        txtMakeYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMakeYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout yearPanelLayout = new javax.swing.GroupLayout(yearPanel);
        yearPanel.setLayout(yearPanelLayout);
        yearPanelLayout.setHorizontalGroup(
            yearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yearPanelLayout.createSequentialGroup()
                .addComponent(txtMakeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMakeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        yearPanelLayout.setVerticalGroup(
            yearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtMakeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMakeYear))
        );

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("TO DO A CUSTOMIZED SEARCH : CLICK ON THE RED PANE \"CLICK HERE\" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSearchBySeats, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearchBySerial, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnSearchByModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSearchByCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSearchByAvail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSearchByMake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSearchByYear, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(serialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(availPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(makePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchBySeats))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(seatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSearchBySerial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchByModel)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchByCity)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchByAvail)
                        .addGap(28, 28, 28)
                        .addComponent(btnSearchByMake)
                        .addGap(33, 33, 33)
                        .addComponent(btnSearchByYear)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(serialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(modelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(availPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(makePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yearPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));

        btnAllCars1.setText("CLICK HERE!");
        btnAllCars1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllCars1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("WANNA CHECKOUT ALL THE CARS?");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("WANNA ADVANCED SEARCH?");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("YOUR CAR IS JUST A CLICK AWAY!");

        btnBook.setText("Book Your Ride!");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAllCars1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel7)
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAllCars1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Superclarendon", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("HELLO THERE!");

        jLabel10.setFont(new java.awt.Font("Superclarendon", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("WELCOME BACK TO UBER !");

        jLabel15.setFont(new java.awt.Font("Superclarendon", 2, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("HOPE YOU HAVE A SAFE AND HAPPY JOURNEY!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(310, 310, 310)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jLabel10)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        BookRideJPanel panel = new BookRideJPanel(userProcessContainer,carRecord);
        userProcessContainer.add("BookRideJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchBySeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBySeatsActionPerformed
        // TODO add your handling code here:
        makePanel.setVisible(false);
        seatPanel.setVisible(true);
        serialPanel.setVisible(false);
        cityPanel.setVisible(false);
        modelPanel.setVisible(false);
        yearPanel.setVisible(false);
        availPanel.setVisible(false);

    }//GEN-LAST:event_btnSearchBySeatsActionPerformed

    private void btnSearchBySerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBySerialActionPerformed
        // TODO add your handling code here:
        makePanel.setVisible(false);
        seatPanel.setVisible(false);
        serialPanel.setVisible(true);
        cityPanel.setVisible(false);
        modelPanel.setVisible(false);
        yearPanel.setVisible(false);
        availPanel.setVisible(false);

    }//GEN-LAST:event_btnSearchBySerialActionPerformed

    private void btnSearchByModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByModelActionPerformed
        // TODO add your handling code here:
        makePanel.setVisible(false);
        seatPanel.setVisible(false);
        serialPanel.setVisible(false);
        cityPanel.setVisible(false);
        modelPanel.setVisible(true);
        yearPanel.setVisible(false);
        availPanel.setVisible(false);

    }//GEN-LAST:event_btnSearchByModelActionPerformed

    private void btnSearchByCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByCityActionPerformed
        // TODO add your handling code here:
        makePanel.setVisible(false);
        seatPanel.setVisible(false);
        serialPanel.setVisible(false);
        cityPanel.setVisible(true);
        modelPanel.setVisible(false);
        yearPanel.setVisible(false);
        availPanel.setVisible(false);

    }//GEN-LAST:event_btnSearchByCityActionPerformed

    private void btnSearchByAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByAvailActionPerformed
        // TODO add your handling code here:
        makePanel.setVisible(false);
        seatPanel.setVisible(false);
        serialPanel.setVisible(false);
        cityPanel.setVisible(false);
        modelPanel.setVisible(false);
        yearPanel.setVisible(false);
        availPanel.setVisible(true);

    }//GEN-LAST:event_btnSearchByAvailActionPerformed

    private void btnSearchByMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByMakeActionPerformed
        // TODO add your handling code here:
        makePanel.setVisible(true);
        seatPanel.setVisible(false);
        serialPanel.setVisible(false);
        cityPanel.setVisible(false);
        modelPanel.setVisible(false);
        yearPanel.setVisible(false);
        availPanel.setVisible(false);
    }//GEN-LAST:event_btnSearchByMakeActionPerformed

    private void btnSearchByYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByYearActionPerformed
        // TODO add your handling code here:
        makePanel.setVisible(false);
        seatPanel.setVisible(false);
        serialPanel.setVisible(false);
        cityPanel.setVisible(false);
        modelPanel.setVisible(false);
        yearPanel.setVisible(true);
        availPanel.setVisible(false);
    }//GEN-LAST:event_btnSearchByYearActionPerformed

    private void btnAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAvailableActionPerformed

    private void btnAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailActionPerformed
        try {
            // TODO add your handling code here:
            String avail;
            if(btnAvailable.isSelected()){
                avail = "Available";
            }else{
                avail = "Not Available";
            }

            SearchJPanel panel = new SearchJPanel(userProcessContainer,carRecord,"Availability",avail,"",user,elasticSearchClass);
            userProcessContainer.add("SearchJPanelAvailability",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            makePanel.setVisible(false);
            seatPanel.setVisible(false);
            serialPanel.setVisible(false);
            cityPanel.setVisible(false);
            modelPanel.setVisible(false);
            yearPanel.setVisible(false);
            availPanel.setVisible(false);

        } catch (ParseException ex) {
            Logger.getLogger(CarCustomerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAvailActionPerformed

    private void txtMinSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinSeatsActionPerformed

    private void txtMaxSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxSeatsActionPerformed

    private void btnSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeatsActionPerformed
        try {
            // TODO add your handling code here:
            System.out.println("min seats="+txtMinSeats.getText());
            System.out.println("max seats="+txtMaxSeats.getText());
            SearchJPanel panel = new SearchJPanel(userProcessContainer,carRecord,"ReqSeats",txtMinSeats.getText(),txtMaxSeats.getText(),user,elasticSearchClass);
            userProcessContainer.add("SearchJPanelReqSeats",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtMinSeats.setText("");
            makePanel.setVisible(false);
            seatPanel.setVisible(false);
            serialPanel.setVisible(false);
            cityPanel.setVisible(false);
            modelPanel.setVisible(false);
            yearPanel.setVisible(false);
            availPanel.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(CarCustomerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSeatsActionPerformed

    private void btnSerial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerial1ActionPerformed
        try {
            // TODO add your handling code here:
            SearchJPanel panel = new SearchJPanel(userProcessContainer,carRecord,"Serial",txtSerial1.getText(),"",user,elasticSearchClass);
            userProcessContainer.add("SearchJPanelSerial",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtSerial1.setText("");
            makePanel.setVisible(false);
            seatPanel.setVisible(false);
            serialPanel.setVisible(false);
            cityPanel.setVisible(false);
            modelPanel.setVisible(false);
            yearPanel.setVisible(false);
            availPanel.setVisible(false);

        } catch (ParseException ex) {
            Logger.getLogger(CarCustomerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSerial1ActionPerformed

    private void btnModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelActionPerformed
        try {
            // TODO add your handling code here:
            SearchJPanel panel = new SearchJPanel(userProcessContainer,carRecord,"Model",txtModel.getText(),"",user,elasticSearchClass);
            userProcessContainer.add("SearchJPanelModel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtModel.setText("");
            makePanel.setVisible(false);
            seatPanel.setVisible(false);
            serialPanel.setVisible(false);
            cityPanel.setVisible(false);
            modelPanel.setVisible(false);
            yearPanel.setVisible(false);
            availPanel.setVisible(false);

        } catch (ParseException ex) {
            Logger.getLogger(CarCustomerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModelActionPerformed

    private void btnMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeActionPerformed
        try {
            // TODO add your handling code here:
            SearchJPanel panel = new SearchJPanel(userProcessContainer,carRecord,"Make",txtMake.getText(),"",user,elasticSearchClass);
            userProcessContainer.add("SearchJPanelMake",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtMake.setText("");
            makePanel.setVisible(false);
            seatPanel.setVisible(false);
            serialPanel.setVisible(false);
            cityPanel.setVisible(false);
            modelPanel.setVisible(false);
            yearPanel.setVisible(false);
            availPanel.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(CarCustomerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMakeActionPerformed

    private void txtMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMakeActionPerformed

    private void btnTravelCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelCityActionPerformed
        try {
            // TODO add your handling code here:
            SearchJPanel panel = new SearchJPanel(userProcessContainer,carRecord,"City",txtTravelCity.getText(),"",user,elasticSearchClass);
            userProcessContainer.add("SearchJPanelTravelCity",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtTravelCity.setText("");
            makePanel.setVisible(false);
            seatPanel.setVisible(false);
            serialPanel.setVisible(false);
            cityPanel.setVisible(false);
            modelPanel.setVisible(false);
            yearPanel.setVisible(false);
            availPanel.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(CarCustomerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTravelCityActionPerformed

    private void btnMakeYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeYearActionPerformed
        try {
            // TODO add your handling code here:
            SearchJPanel panel = new SearchJPanel(userProcessContainer,carRecord,"MakeYear",txtMakeYear.getText(),"",user,elasticSearchClass);
            userProcessContainer.add("SearchJPanelMakeYear",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            txtMakeYear.setText("");
            makePanel.setVisible(false);
            seatPanel.setVisible(false);
            serialPanel.setVisible(false);
            cityPanel.setVisible(false);
            modelPanel.setVisible(false);
            yearPanel.setVisible(false);
            availPanel.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(CarCustomerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMakeYearActionPerformed

    private void txtMakeYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMakeYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMakeYearActionPerformed

    private void btnAllCars1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllCars1ActionPerformed
        try {
            // TODO add your handling code here:
            SearchJPanel panel = new SearchJPanel(userProcessContainer,carRecord,"All","","",user,elasticSearchClass);
            userProcessContainer.add("SearchJPanelAll",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } catch (ParseException ex) {
            Logger.getLogger(CarCustomerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAllCars1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel availPanel;
    private javax.swing.JButton btnAllCars1;
    private javax.swing.JButton btnAvail;
    private javax.swing.JRadioButton btnAvailable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnMake;
    private javax.swing.JButton btnMakeYear;
    private javax.swing.JButton btnModel;
    private javax.swing.JRadioButton btnNotAvailable;
    private javax.swing.JButton btnSearchByAvail;
    private javax.swing.JButton btnSearchByCity;
    private javax.swing.JButton btnSearchByMake;
    private javax.swing.JButton btnSearchByModel;
    private javax.swing.JButton btnSearchBySeats;
    private javax.swing.JButton btnSearchBySerial;
    private javax.swing.JButton btnSearchByYear;
    private javax.swing.JButton btnSeats;
    private javax.swing.JButton btnSerial1;
    private javax.swing.JButton btnTravelCity;
    private javax.swing.JPanel cityPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel makePanel;
    private javax.swing.JPanel modelPanel;
    private javax.swing.JPanel seatPanel;
    private javax.swing.JPanel serialPanel;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtMakeYear;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtMinSeats;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSerial1;
    private javax.swing.JTextField txtTravelCity;
    private javax.swing.JPanel yearPanel;
    // End of variables declaration//GEN-END:variables
}
