/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarRecord;
import ElasticSearch.ElasticSearchClass;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.awt.CardLayout;
import java.io.IOException;
import static java.lang.Boolean.TRUE;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author manasa
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private CarRecord carRecord;
    private JPanel userProcessContainer;
    private final ElasticSearchClass elasticSearchClass;

    public CreateJPanel(JPanel userProcessContainer, CarRecord carRecord,ElasticSearchClass elasticSearchClass) throws IOException {
        initComponents();
        this.carRecord = carRecord;
        this.userProcessContainer = userProcessContainer;
        this.elasticSearchClass = elasticSearchClass;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblCreateAccount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCarDesc = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        txtCarModel = new javax.swing.JTextField();
        txtMakeYear = new javax.swing.JTextField();
        txtAdd = new javax.swing.JButton();
        txtSerial = new javax.swing.JTextField();
        txtMaintenanceDate = new javax.swing.JTextField();
        txtCarCity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumSeats = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 0));
        setForeground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCreateAccount.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCreateAccount.setForeground(new java.awt.Color(204, 204, 204));
        lblCreateAccount.setText("NEW CAR ADDITION FORM");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("CAR DESCRIPTION:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("MODEL:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("MAKE:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("YEAR OF MAKE:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtCarDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarDescActionPerformed(evt);
            }
        });

        txtCarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarModelActionPerformed(evt);
            }
        });

        txtAdd.setText("ADD A CAR");
        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });

        txtSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialActionPerformed(evt);
            }
        });

        txtCarCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarCityActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("SERIAL NUMBER:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("CITY:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("MAINTENANCE DATE:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("NUMBER OF SEATS:");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("All the fields are Mandatory!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)))
                        .addGap(0, 434, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNumSeats)
                            .addComponent(txtCarDesc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCarModel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMake, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMakeYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSerial)
                            .addComponent(txtCarCity)
                            .addComponent(txtMaintenanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMakeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarCity, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaintenanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(44, 44, 44)
                .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCarDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarDescActionPerformed

    private void txtCarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarModelActionPerformed

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        // TODO add your handling code here:
        String error = "";
        if(txtCarDesc.getText().equalsIgnoreCase("") || (txtMake.getText().equalsIgnoreCase(""))
                || (txtCarModel.getText().equalsIgnoreCase(""))|| (txtMakeYear.getText().equalsIgnoreCase(""))
                || (txtSerial.getText().equalsIgnoreCase(""))|| (txtMaintenanceDate.getText().equalsIgnoreCase(""))
                || (txtCarCity.getText().equalsIgnoreCase(""))|| (txtNumSeats.getText().equalsIgnoreCase(""))){
            error="\nAll the fields are Mandatory!!!";
        }       
        if(!error.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null,error);
        }else{
            String cityRegex = "^[a-zA-Z][a-zA-Z ]+[a-zA-Z]$";
            Pattern cityPattern = Pattern.compile(cityRegex);
            Matcher checkCity = cityPattern.matcher(txtCarCity.getText());
            boolean checkCityMatch = checkCity.matches();
            if(!(checkCityMatch == TRUE)){
                error ="\nCity needs to be valid - only Alphabets and Spaces allowed!";
            }
            String numRegex = "^[0-9]{4}$";
            Pattern numPattern = Pattern.compile(numRegex);
            Matcher checkNum= numPattern.matcher(txtMakeYear.getText());
            boolean checkNumMatch = checkNum.matches();
            if(!(checkNumMatch == TRUE)){
                error ="\nMake Year needs to be digits only -[YYYY] Pattern!";
            }
            try{
             SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
             String dateString = txtMaintenanceDate.getText();

             String formattedDate = fmt.format(fmt.parse(dateString));
             if (!(formattedDate.equals(dateString))) {
                error+="\nFor Maintenance Month - Please enter in \"dd/MM/yyyy\" pattern only!"; 
             } 
        }catch (ParseException ex) {
                error+="\nFor Maintenance Month - Please enter in \"dd/MM/yyyy\" pattern only!"; 
            } 


            if(!error.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null,error);
            }else{
                 String carDesc = txtCarDesc.getText();
                 String carModel = txtCarModel.getText();
                 int carMakeYear = Integer.parseInt(txtMakeYear.getText());
                 int totalSeats = Integer.parseInt(txtNumSeats.getText());
                 String carMake = txtMake.getText();
                 String carSerialNum = txtSerial.getText();
                 String carCity = txtCarCity.getText();
                 String maintenanceDate = txtMaintenanceDate.getText();
                 
                    Car car = carRecord.addCar();
                    
                    car.setCarAvailability(true);
                    car.setCarCity(carCity);
                    car.setCarDesc(carDesc);
                    car.setCarMake(carMake);
                    car.setCarMakeYear(carMakeYear);
                    car.setCarModel(carModel);
                    car.setCarSerialNum(carSerialNum);
                    car.setMaintenanceDate(maintenanceDate);
                    car.setSeatsAvail(totalSeats);
                    car.setTotalSeats(totalSeats);
                    
 
                try {
                    elasticSearchClass.save(car);
                } catch (IOException ex) {
                    Logger.getLogger(CreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }


                    JOptionPane.showMessageDialog(null,"Car Added Succesfully!!!");
                            txtCarDesc.setText(car.getCarDesc());
        txtCarModel.setText("");
        txtMakeYear.setText("");
        txtNumSeats.setText("");
        txtMake.setText("");
        txtSerial.setText("");
        txtCarCity.setText("");
        txtCarDesc.setText("");
        txtMaintenanceDate.setText("");

            }
        }
    }//GEN-LAST:event_txtAddActionPerformed

    private void txtSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialActionPerformed

    private void txtCarCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JButton txtAdd;
    private javax.swing.JTextField txtCarCity;
    private javax.swing.JTextField txtCarDesc;
    private javax.swing.JTextField txtCarModel;
    private javax.swing.JTextField txtMaintenanceDate;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtMakeYear;
    private javax.swing.JTextField txtNumSeats;
    private javax.swing.JTextField txtSerial;
    // End of variables declaration//GEN-END:variables
}
