/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import java.awt.CardLayout;
import static java.lang.Boolean.TRUE;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author karthik
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private JPanel userProcessContainer;
    private Car car;
    private String user;
    public ViewJPanel(JPanel userProcessContainer,Car car,String user) {
        initComponents();
    
        if(user.equalsIgnoreCase("admin")){
    
            btnSave.setVisible(true);
            btnUpdate.setVisible(true);
        }else{
            btnSave.setVisible(false);
            btnUpdate.setVisible(false);            
        }
        this.userProcessContainer = userProcessContainer;
        this.car = car;
        this.user = user;
        populateCarDetails();
    }
    private void populateCarDetails(){
        txtCarDesc.setText(car.getCarDesc());
        txtCarModel.setText(car.getCarModel());
        txtMakeYear.setText(String.valueOf(car.getCarMakeYear()));
        txtNumSeats.setText(String.valueOf(car.getTotalSeats()));
        txtMake.setText((car.getCarMake()));
        txtSerial.setText(car.getCarSerialNum());
        txtCarCity.setText(car.getCarCity());
        txtMaintenanceDate.setText(String.valueOf(car.getMaintenanceDate()));
        if(car.isCarAvailability()){
        txtAvailability.setText(String.valueOf("AVAILABLE"));
        }else{
        txtAvailability.setText(String.valueOf("NOT AVAILABLE"));    
        }
                
        txtSeatsAvailable.setText(String.valueOf(car.getSeatsAvail()));        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblCreateAccount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCarDesc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        txtCarModel = new javax.swing.JTextField();
        txtMakeYear = new javax.swing.JTextField();
        txtNumSeats = new javax.swing.JTextField();
        txtSerial = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSeatsAvailable = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCarCity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAvailability = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMaintenanceDate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 102));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCreateAccount.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblCreateAccount.setForeground(new java.awt.Color(204, 204, 204));
        lblCreateAccount.setText("View Car Detail");

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("CITY:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtCarDesc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCarDesc.setEnabled(false);
        txtCarDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarDescActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("SEATS AVAILABLE:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtMake.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMake.setEnabled(false);

        txtCarModel.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCarModel.setEnabled(false);
        txtCarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarModelActionPerformed(evt);
            }
        });

        txtMakeYear.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMakeYear.setEnabled(false);

        txtNumSeats.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNumSeats.setEnabled(false);

        txtSerial.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSerial.setEnabled(false);
        txtSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("NUMBER OF SEATS:");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtSeatsAvailable.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSeatsAvailable.setEnabled(false);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("CAR DESCRIPTION:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtCarCity.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCarCity.setEnabled(false);
        txtCarCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarCityActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("MODEL:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("MAKE:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("SERIAL NUMBER:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("YEAR OF MAKE:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtAvailability.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAvailability.setEnabled(false);

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("AVAILABILITY:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtMaintenanceDate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaintenanceDate.setEnabled(false);

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("MAINTENANCE DATE:");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(lblCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNumSeats)
                            .addComponent(txtCarDesc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCarModel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMake, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMakeYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaintenanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSerial)
                                        .addComponent(txtCarCity)
                                        .addComponent(txtSeatsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateAccount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMakeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCarCity, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSeatsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaintenanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCarDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarDescActionPerformed

    private void txtCarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarModelActionPerformed

    private void txtSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialActionPerformed

    private void txtCarCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarCityActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        txtCarDesc.setEnabled(true);
        txtCarCity.setEnabled(true);
        txtCarModel.setEnabled(true);
        txtMake.setEnabled(true);
        txtMakeYear.setEnabled(true);
        txtNumSeats.setEnabled(true);
        txtMaintenanceDate.setEnabled(true);
        txtSerial.setEnabled(true);
        txtSeatsAvailable.setEnabled(true);
        txtAvailability.setEnabled(true);
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        
        String error = "";
        if(txtCarDesc.getText().equalsIgnoreCase("") || (txtMake.getText().equalsIgnoreCase(""))
                || (txtCarModel.getText().equalsIgnoreCase(""))|| (txtMakeYear.getText().equalsIgnoreCase(""))
                || (txtSerial.getText().equalsIgnoreCase(""))|| (txtMaintenanceDate.getText().equalsIgnoreCase(""))
                || (txtCarCity.getText().equalsIgnoreCase(""))|| (txtNumSeats.getText().equalsIgnoreCase(""))){
            error="\nAll the fields are Mandatory!!!";
        }       
        if(!error.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null,error);
        }else{
            String cityRegex = "^[a-zA-Z][a-zA-Z ]+[a-zA-Z]$";
            Pattern cityPattern = Pattern.compile(cityRegex);
            Matcher checkCity = cityPattern.matcher(txtCarCity.getText());
            boolean checkCityMatch = checkCity.matches();
            if(!(checkCityMatch == TRUE)){
                error ="\nCity needs to be valid - only Alphabets and Spaces allowed!";
            }
            String numRegex = "^[0-9]{4}$";
            Pattern numPattern = Pattern.compile(numRegex);
            Matcher checkNum= numPattern.matcher(txtMakeYear.getText());
            boolean checkNumMatch = checkNum.matches();
            if(!(checkNumMatch == TRUE)){
                error ="\nMake Year needs to be digits only -[YYYY] Pattern!";
            }
            Matcher checkNum2= numPattern.matcher(txtNumSeats.getText());
            boolean checkNum2Match = checkNum2.matches();
            if(!(checkNumMatch == TRUE)){
                error ="\nNumber of Seats need to be digits only!";
            }
            Matcher checkNum3= numPattern.matcher(txtSeatsAvailable.getText());
            boolean checkNum3Match = checkNum3.matches();
            if(!(checkNumMatch == TRUE)){
                error ="\nSeats Available need to be digits only!";
            }
            try{
             SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
             String dateString = txtMaintenanceDate.getText();

             String formattedDate = fmt.format(fmt.parse(dateString));
             if (!(formattedDate.equals(dateString))) {
                error+="\nFor Maintenance Month - Please enter in \"dd/MM/yyyy\" pattern only!"; 
             } 
        }catch (ParseException ex) {
                error+="\nFor Maintenance Month - Please enter in \"dd/MM/yyyy\" pattern only!"; 
            } 


            if(!error.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null,error);
            }else{
                 String carDesc = txtCarDesc.getText();
                 String carModel = txtCarModel.getText();
                 int carMakeYear = Integer.parseInt(txtMakeYear.getText());
                 int totalSeats = Integer.parseInt(txtNumSeats.getText());
                 String carMake = txtMake.getText();
                 String carSerialNum = txtSerial.getText();
                 String carCity = txtCarCity.getText();
                 String maintenanceDate = txtMaintenanceDate.getText();                
                    if(Integer.parseInt(txtSeatsAvailable.getText())<=0){
                    car.setCarAvailability(false);
                    }else{
                    car.setCarAvailability(true);    
                    }
                    car.setCarCity(carCity);
                    car.setCarDesc(carDesc);
                    car.setCarMake(carMake);
                    car.setCarMakeYear(carMakeYear);
                    car.setCarModel(carModel);
                    car.setCarSerialNum(carSerialNum);
                    car.setMaintenanceDate(maintenanceDate);
                    car.setSeatsAvail(totalSeats);
                    car.setTotalSeats(totalSeats);
 
         JOptionPane.showMessageDialog(null,"Car Details Saved Succesfully!!!");
        txtCarDesc.setText("");
        txtCarModel.setText("");
        txtMakeYear.setText("");
        txtNumSeats.setText("");
        txtMake.setText("");
        txtSerial.setText("");
        txtCarCity.setText("");
        txtCarDesc.setText("");
        txtMaintenanceDate.setText("");
        txtAvailability.setText("");
        txtSeatsAvailable.setText("");

        }
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtCarCity;
    private javax.swing.JTextField txtCarDesc;
    private javax.swing.JTextField txtCarModel;
    private javax.swing.JTextField txtMaintenanceDate;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtMakeYear;
    private javax.swing.JTextField txtNumSeats;
    private javax.swing.JTextField txtSeatsAvailable;
    private javax.swing.JTextField txtSerial;
    // End of variables declaration//GEN-END:variables
}
